markdown: kramdown
permalink: none
plugins: [jekyll-sitemap,  jekyll-seo-tag]

title: Duong / designs

defaults:
  -
    scope:
      path: "projects"
    values:
      permalink: /:basename

exclude: [bundle]

sass:
  sass_dir: assets/css
  style: :nested
