menu:
- {name: 'Projects', url: ''}
- {name: 'About', url: 'pages/about.html'}

seo:
  description: 'Nguyen Hoang Duong''s art and design portfolio'
  rel-author:
  rel-publisher:

projects:
- {name: '42tm''s Linux Command Line Guide', folder: 'lclg', file: 'projects/lclg.html'}
- {name: 'Websites', folder: 'websites', file: 'projects/websites.html'}

social:
- {icon: 'instagram', link: 'https://www.instagram.com/you_create.designs'}
- {icon: 'github', link: 'https://github.com/you-create'}
- {icon: 'dribbble', link: 'https://dribbble.com/you_create'}
- {icon: 'soundcloud', link: 'https://soundcloud.com/user-235709988'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
