# Site

menu:
- {name: 'Projects', url: ''}
# - {name: 'Blog', url: 'pages/blog.html'}
- {name: 'About', url: 'pages/about.html'}
- {name: 'Contact', url: 'pages/contact.html'}

# SEO

seo:
  description: 'Nguyen Hoang Duong''s art and design portfolio'
  rel-author:
  rel-publisher:

# Google Analytics

google-analytics-ua: ''

# 'About' Section

about: >
  # Portfolio Jekyll Theme

  This is a personal portfolio theme that I built from the ground up, using the [DevTips Starter Kit](http://devtipsstarterkit.com/) as a foundation for starting, and following closely the amazing tutorial by [Travis Neilson over at DevTips](https://www.youtube.com/watch?v=T6jKLsxbFg4&list=PL0CB3OvPhDA_STygmp3sDenx3UpdOMk7P). You can [check out the demo](lenpaul.github.io/portfolio-jekyll-theme/), and [fork the repository](https://github.com/LeNPaul/portfolio-jekyll-theme/fork), to get started.

# 'Contact' Section

contact: >
  # Contact

  You may contact me [through my email](mailto:l.nguyen.paul@gmail.com) or [tweet at me](https://twitter.com/intent/tweet?text=%40paululele) if you have any questions or would like to bring up any issues.

# Projects

projects:
- {name: '42tm''s Linux Command Line Guide', folder: 'lclg', file: 'projects/lclg.html'}

# Social

social:
- {icon: 'instagram', link: 'you_create.designs'}
- {icon: 'github', link: 'you-create'}
- {icon: 'dribbble', link: 'you_create'}
- {icon: 'soundcloud', link: 'user-235709988'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
