menu:
- {name: 'Projects', url: ''}
- {name: 'About', url: 'pages/about.html'}

seo:
  description: 'Nguyen Hoang Duong''s art and design portfolio'
  rel-author:
  rel-publisher:

projects:
- {name: 'Dandelion', folder: 'dandelion', file: 'dandelion.html' }
- {name: 'Donuts', folder: 'donuts', file: 'donuts.html' }
- {name: 'Websites', folder: 'websites', file: 'websites.html'}
- {name: '2D vector', folder: '2d-vector', file: '2d-vector.html'}
- {name: 'Logos', folder: 'logos', file: 'logos.html'}
- {name: 'Linux Command Line Guide', folder: 'lclg', file: 'lclg.html'}
- {name: '356', folder: '356', file: '356.html'}

social:
- {icon: 'instagram', link: 'https://www.instagram.com/thechonkypenguin'}
- {icon: 'github', link: 'https://github.com/you-create'}
- {icon: 'dribbble', link: 'https://dribbble.com/you_create'}
- {icon: 'soundcloud', link: 'https://soundcloud.com/user-235709988'}

# social network icons available:
# 'twitter' / 'facebook' / 'github' / 'pinterest' / 'google-plus' / 'linkedin' /
# 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
